//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriciaBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccessToken {
            get {
                return ((string)(this["AccessToken"]));
            }
            set {
                this["AccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccessSecret {
            get {
                return ((string)(this["AccessSecret"]));
            }
            set {
                this["AccessSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long LastGettedID {
            get {
                return ((long)(this["LastGettedID"]));
            }
            set {
                this["LastGettedID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long LastGettedReplyID {
            get {
                return ((long)(this["LastGettedReplyID"]));
            }
            set {
                this["LastGettedReplyID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user.sqlite3")]
        public string DatabaseFileName {
            get {
                return ((string)(this["DatabaseFileName"]));
            }
            set {
                this["DatabaseFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("create table user(id LONG  PRIMARY KEY, name TEXT, screen_name TEXT,nick_name TEX" +
            "T, mail TEXT)")]
        public string DBCreateUserTable {
            get {
                return ((string)(this["DBCreateUserTable"]));
            }
            set {
                this["DBCreateUserTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from user")]
        public string DBSelectUserTable {
            get {
                return ((string)(this["DBSelectUserTable"]));
            }
            set {
                this["DBSelectUserTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2354246292")]
        public long MyUserID {
            get {
                return ((long)(this["MyUserID"]));
            }
            set {
                this["MyUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("create table whitelist(id LONG PRIMARY KEY)")]
        public string DBCreateWhiteListTable {
            get {
                return ((string)(this["DBCreateWhiteListTable"]));
            }
            set {
                this["DBCreateWhiteListTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from whitelist")]
        public string DBSelectWhiteListTable {
            get {
                return ((string)(this["DBSelectWhiteListTable"]));
            }
            set {
                this["DBSelectWhiteListTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tricia.disraeli@gmail.com")]
        public string MyMailAddress {
            get {
                return ((string)(this["MyMailAddress"]));
            }
            set {
                this["MyMailAddress"] = value;
            }
        }
    }
}
